### PR TITLE
Add Crockpot settings and status query.

### PR DESCRIPTION
**Pull request by gitbisector**
Added HOT | LOW | WARM | POTSTATE to work with Belkin Wemo enabled Crockpot.

### CODE REVIEW

**Comment by agilemation** [comment]
Hey, this is great!!  Thank you for adding that in, I will get it merged in once I have had a proper look.  Just wanted to check if there is any implication to pulling out the call to filterHumanizeBinary on line 211 tomorrow before I do.

Thanks again and I will try and merge, publish to github, npm, etc so you can use the trunk version with ease should you use npm or anything like that to install it.

P.S.  Apologies for the delay, this github account goes to an email address I don't check too often and I have only just seen your pull request.

**Comment by agilemation** [comment]
Hey, okay I had a look at this and although don't think it causes me issues, think it might cause one for the people I originally wrote it for.  Over this weekend I will properly comment and fix this and merge in your change.  Thanks again for your help with adding the crockpot options!!  Its great to have this and I will add your name into the acknowledgements if you'd like?  Or I can just acknowledge you by your github handle if you prefer?

**Comment by gitbisector** [comment]
No worries on the delay, thanks for putting this out here. Got me started in no time. I've been running with this commit for some time now.

**Comment by agilemation** [comment]
Hey, again, apologies for the delay in doing this.  I started looking at it and have integrated your change into a bigger one I wanted to do when writing this (but wasn't given the time to do at the company I was working at - they only cared that things worked, maintainability or open sourcing was not a concern they shared).  Basically, the change I have is to move the XML snippets out of the code and into parametrised template files so I can use a more generic SOAP function and get the duplication (and XML) :-) out of the 'wemo' command executable.  Reason I haven't pushed this to GitHub yet is that I don't have a Belkin WeMo of my own as I wrote this for a company I worked at.

If you are able and would like to test my change for me that I haven't broken it when it talks to a WeMo then I will push the branch to GitHub or send you a tar or something (let me know whats good for you if so)?  If not, I will do it once I have managed to get a WeMo to test with.

Thanks regardless,

James

P.S. I also have a change to add the ability to scan the local LAN for WeMo devices and do the initial setup, so if you'd like to test that and have the time, etc. let me know and I can do that too! :-)

**Pull request closed without merging**
